spring:
  config:
    import: classpath:.env.properties
  cloud:
    gcp:
      project-id: tr4-2024-06-deutschebank
      credentials:
        location:

booking:
  event:
    subscription: "EmailSub"

sendgrid:
  api-key: ${SEND_GRID_API_KEY}

email:
  from: ${FROM_EMAIL}

server:
  port: ${PORT:8080}