spring:
  config:
    import: classpath:.env.properties
  cloud:
    gcp:
      project-id: tr4-2024-06-deutschebank
      credentials:
        location: classpath:tr4-2024-06-deutschebank-980dbd13eab7.json

booking:
  event:
    subscription: "MyTopic-sub"

sendgrid:
  api-key: ${SEND_GRID_API_KEY}

email:
  from: ${FROM_EMAIL}

server:
  port: 8080